apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/no-provisioner # use this instead of minikube provisioner as it not able to dynamic provisioning between nodes
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer