apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: phpmyadmin
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007