apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-main-bind
subjects:
- kind: User
  name: aiman
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: user-main
  apiGroup: rbac.authorization.k8s.io